
# search radius for players, ItemFinder.find.admin removes the max_search_radius for admins. 
# There is still a builtin max radius of 1000 to prevent clumsy admins from crashing the server :)
default_search_radius: 20
max_search_radius: 50

# time chests stay marked in ticks
marker_timeout: 500

# If enabled, the plugin will also search shulkerboxes inside chests. 
search_shulkerbox_recursively: true

messages:
  error:
    unknown_material: "Material %s does not exist."
    must_be_ingame: "You must be ingame to use this command"
  info:
    search: "Searching for %s in a radius of %d blocks."
    found:
      total: "Found %d items in total: "
      container: "Chests: %d"
      player: "Inventory: %d"
      ender: "EnderChest: %d"
      nothingFound: "%s could not be found"
