name: ItemFinder
main: me.lennartVH01.ItemFinder
version: 0.1
description: Simple container searching plugin
author: lennartVH01

commands:
  find:
    description: Search nearby chests
    permission: ItemFinder.find
    usage: "Usage: /<command> <itemName> <searchRadius>"

permissions:
  ItemFinder.find:
    description: "Gives access to /find"
    default: true